/* eslint-disable camelcase */
export const bookPrStargazers = [
  {
    login: 'glenux',
    id: 81168,
    node_id: 'MDQ6VXNlcjgxMTY4',
    avatar_url: 'https://avatars.githubusercontent.com/u/81168?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/glenux',
    html_url: 'https://github.com/glenux',
    followers_url: 'https://api.github.com/users/glenux/followers',
    following_url: 'https://api.github.com/users/glenux/following{/other_user}',
    gists_url: 'https://api.github.com/users/glenux/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/glenux/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/glenux/subscriptions',
    organizations_url: 'https://api.github.com/users/glenux/orgs',
    repos_url: 'https://api.github.com/users/glenux/repos',
    events_url: 'https://api.github.com/users/glenux/events{/privacy}',
    received_events_url: 'https://api.github.com/users/glenux/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mwchase',
    id: 882845,
    node_id: 'MDQ6VXNlcjg4Mjg0NQ==',
    avatar_url: 'https://avatars.githubusercontent.com/u/882845?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mwchase',
    html_url: 'https://github.com/mwchase',
    followers_url: 'https://api.github.com/users/mwchase/followers',
    following_url:
      'https://api.github.com/users/mwchase/following{/other_user}',
    gists_url: 'https://api.github.com/users/mwchase/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mwchase/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mwchase/subscriptions',
    organizations_url: 'https://api.github.com/users/mwchase/orgs',
    repos_url: 'https://api.github.com/users/mwchase/repos',
    events_url: 'https://api.github.com/users/mwchase/events{/privacy}',
    received_events_url: 'https://api.github.com/users/mwchase/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'michaelsmanley',
    id: 93241,
    node_id: 'MDQ6VXNlcjkzMjQx',
    avatar_url: 'https://avatars.githubusercontent.com/u/93241?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/michaelsmanley',
    html_url: 'https://github.com/michaelsmanley',
    followers_url: 'https://api.github.com/users/michaelsmanley/followers',
    following_url:
      'https://api.github.com/users/michaelsmanley/following{/other_user}',
    gists_url: 'https://api.github.com/users/michaelsmanley/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/michaelsmanley/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/michaelsmanley/subscriptions',
    organizations_url: 'https://api.github.com/users/michaelsmanley/orgs',
    repos_url: 'https://api.github.com/users/michaelsmanley/repos',
    events_url: 'https://api.github.com/users/michaelsmanley/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/michaelsmanley/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'chivandikwa',
    id: 5655789,
    node_id: 'MDQ6VXNlcjU2NTU3ODk=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5655789?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/chivandikwa',
    html_url: 'https://github.com/chivandikwa',
    followers_url: 'https://api.github.com/users/chivandikwa/followers',
    following_url:
      'https://api.github.com/users/chivandikwa/following{/other_user}',
    gists_url: 'https://api.github.com/users/chivandikwa/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/chivandikwa/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/chivandikwa/subscriptions',
    organizations_url: 'https://api.github.com/users/chivandikwa/orgs',
    repos_url: 'https://api.github.com/users/chivandikwa/repos',
    events_url: 'https://api.github.com/users/chivandikwa/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/chivandikwa/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JeffersonHuang',
    id: 47512530,
    node_id: 'MDQ6VXNlcjQ3NTEyNTMw',
    avatar_url: 'https://avatars.githubusercontent.com/u/47512530?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JeffersonHuang',
    html_url: 'https://github.com/JeffersonHuang',
    followers_url: 'https://api.github.com/users/JeffersonHuang/followers',
    following_url:
      'https://api.github.com/users/JeffersonHuang/following{/other_user}',
    gists_url: 'https://api.github.com/users/JeffersonHuang/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/JeffersonHuang/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/JeffersonHuang/subscriptions',
    organizations_url: 'https://api.github.com/users/JeffersonHuang/orgs',
    repos_url: 'https://api.github.com/users/JeffersonHuang/repos',
    events_url: 'https://api.github.com/users/JeffersonHuang/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/JeffersonHuang/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'lfkrebs',
    id: 11545382,
    node_id: 'MDQ6VXNlcjExNTQ1Mzgy',
    avatar_url: 'https://avatars.githubusercontent.com/u/11545382?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/lfkrebs',
    html_url: 'https://github.com/lfkrebs',
    followers_url: 'https://api.github.com/users/lfkrebs/followers',
    following_url:
      'https://api.github.com/users/lfkrebs/following{/other_user}',
    gists_url: 'https://api.github.com/users/lfkrebs/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/lfkrebs/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/lfkrebs/subscriptions',
    organizations_url: 'https://api.github.com/users/lfkrebs/orgs',
    repos_url: 'https://api.github.com/users/lfkrebs/repos',
    events_url: 'https://api.github.com/users/lfkrebs/events{/privacy}',
    received_events_url: 'https://api.github.com/users/lfkrebs/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'alexischecura',
    id: 69598586,
    node_id: 'MDQ6VXNlcjY5NTk4NTg2',
    avatar_url: 'https://avatars.githubusercontent.com/u/69598586?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/alexischecura',
    html_url: 'https://github.com/alexischecura',
    followers_url: 'https://api.github.com/users/alexischecura/followers',
    following_url:
      'https://api.github.com/users/alexischecura/following{/other_user}',
    gists_url: 'https://api.github.com/users/alexischecura/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/alexischecura/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/alexischecura/subscriptions',
    organizations_url: 'https://api.github.com/users/alexischecura/orgs',
    repos_url: 'https://api.github.com/users/alexischecura/repos',
    events_url: 'https://api.github.com/users/alexischecura/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/alexischecura/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'MichaelAdame',
    id: 33136739,
    node_id: 'MDQ6VXNlcjMzMTM2NzM5',
    avatar_url: 'https://avatars.githubusercontent.com/u/33136739?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/MichaelAdame',
    html_url: 'https://github.com/MichaelAdame',
    followers_url: 'https://api.github.com/users/MichaelAdame/followers',
    following_url:
      'https://api.github.com/users/MichaelAdame/following{/other_user}',
    gists_url: 'https://api.github.com/users/MichaelAdame/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/MichaelAdame/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/MichaelAdame/subscriptions',
    organizations_url: 'https://api.github.com/users/MichaelAdame/orgs',
    repos_url: 'https://api.github.com/users/MichaelAdame/repos',
    events_url: 'https://api.github.com/users/MichaelAdame/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/MichaelAdame/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'sparfenyuk',
    id: 134065,
    node_id: 'MDQ6VXNlcjEzNDA2NQ==',
    avatar_url: 'https://avatars.githubusercontent.com/u/134065?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/sparfenyuk',
    html_url: 'https://github.com/sparfenyuk',
    followers_url: 'https://api.github.com/users/sparfenyuk/followers',
    following_url:
      'https://api.github.com/users/sparfenyuk/following{/other_user}',
    gists_url: 'https://api.github.com/users/sparfenyuk/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/sparfenyuk/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/sparfenyuk/subscriptions',
    organizations_url: 'https://api.github.com/users/sparfenyuk/orgs',
    repos_url: 'https://api.github.com/users/sparfenyuk/repos',
    events_url: 'https://api.github.com/users/sparfenyuk/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/sparfenyuk/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'abereghici',
    id: 6989817,
    node_id: 'MDQ6VXNlcjY5ODk4MTc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6989817?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/abereghici',
    html_url: 'https://github.com/abereghici',
    followers_url: 'https://api.github.com/users/abereghici/followers',
    following_url:
      'https://api.github.com/users/abereghici/following{/other_user}',
    gists_url: 'https://api.github.com/users/abereghici/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/abereghici/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/abereghici/subscriptions',
    organizations_url: 'https://api.github.com/users/abereghici/orgs',
    repos_url: 'https://api.github.com/users/abereghici/repos',
    events_url: 'https://api.github.com/users/abereghici/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/abereghici/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'evvrit',
    id: 95182188,
    node_id: 'U_kgDOBaxdbA',
    avatar_url: 'https://avatars.githubusercontent.com/u/95182188?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/evvrit',
    html_url: 'https://github.com/evvrit',
    followers_url: 'https://api.github.com/users/evvrit/followers',
    following_url: 'https://api.github.com/users/evvrit/following{/other_user}',
    gists_url: 'https://api.github.com/users/evvrit/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/evvrit/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/evvrit/subscriptions',
    organizations_url: 'https://api.github.com/users/evvrit/orgs',
    repos_url: 'https://api.github.com/users/evvrit/repos',
    events_url: 'https://api.github.com/users/evvrit/events{/privacy}',
    received_events_url: 'https://api.github.com/users/evvrit/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'akirk',
    id: 203408,
    node_id: 'MDQ6VXNlcjIwMzQwOA==',
    avatar_url: 'https://avatars.githubusercontent.com/u/203408?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/akirk',
    html_url: 'https://github.com/akirk',
    followers_url: 'https://api.github.com/users/akirk/followers',
    following_url: 'https://api.github.com/users/akirk/following{/other_user}',
    gists_url: 'https://api.github.com/users/akirk/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/akirk/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/akirk/subscriptions',
    organizations_url: 'https://api.github.com/users/akirk/orgs',
    repos_url: 'https://api.github.com/users/akirk/repos',
    events_url: 'https://api.github.com/users/akirk/events{/privacy}',
    received_events_url: 'https://api.github.com/users/akirk/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'pfefferle',
    id: 2373,
    node_id: 'MDQ6VXNlcjIzNzM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2373?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/pfefferle',
    html_url: 'https://github.com/pfefferle',
    followers_url: 'https://api.github.com/users/pfefferle/followers',
    following_url:
      'https://api.github.com/users/pfefferle/following{/other_user}',
    gists_url: 'https://api.github.com/users/pfefferle/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/pfefferle/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/pfefferle/subscriptions',
    organizations_url: 'https://api.github.com/users/pfefferle/orgs',
    repos_url: 'https://api.github.com/users/pfefferle/repos',
    events_url: 'https://api.github.com/users/pfefferle/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/pfefferle/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'vitozev',
    id: 1749918,
    node_id: 'MDQ6VXNlcjE3NDk5MTg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1749918?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/vitozev',
    html_url: 'https://github.com/vitozev',
    followers_url: 'https://api.github.com/users/vitozev/followers',
    following_url:
      'https://api.github.com/users/vitozev/following{/other_user}',
    gists_url: 'https://api.github.com/users/vitozev/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/vitozev/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/vitozev/subscriptions',
    organizations_url: 'https://api.github.com/users/vitozev/orgs',
    repos_url: 'https://api.github.com/users/vitozev/repos',
    events_url: 'https://api.github.com/users/vitozev/events{/privacy}',
    received_events_url: 'https://api.github.com/users/vitozev/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'psrpinto',
    id: 550401,
    node_id: 'MDQ6VXNlcjU1MDQwMQ==',
    avatar_url: 'https://avatars.githubusercontent.com/u/550401?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/psrpinto',
    html_url: 'https://github.com/psrpinto',
    followers_url: 'https://api.github.com/users/psrpinto/followers',
    following_url:
      'https://api.github.com/users/psrpinto/following{/other_user}',
    gists_url: 'https://api.github.com/users/psrpinto/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/psrpinto/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/psrpinto/subscriptions',
    organizations_url: 'https://api.github.com/users/psrpinto/orgs',
    repos_url: 'https://api.github.com/users/psrpinto/repos',
    events_url: 'https://api.github.com/users/psrpinto/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/psrpinto/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'MatthiasReinholz',
    id: 9655284,
    node_id: 'MDQ6VXNlcjk2NTUyODQ=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9655284?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/MatthiasReinholz',
    html_url: 'https://github.com/MatthiasReinholz',
    followers_url: 'https://api.github.com/users/MatthiasReinholz/followers',
    following_url:
      'https://api.github.com/users/MatthiasReinholz/following{/other_user}',
    gists_url: 'https://api.github.com/users/MatthiasReinholz/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/MatthiasReinholz/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/MatthiasReinholz/subscriptions',
    organizations_url: 'https://api.github.com/users/MatthiasReinholz/orgs',
    repos_url: 'https://api.github.com/users/MatthiasReinholz/repos',
    events_url:
      'https://api.github.com/users/MatthiasReinholz/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/MatthiasReinholz/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'morgansamson',
    id: 6242918,
    node_id: 'MDQ6VXNlcjYyNDI5MTg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6242918?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/morgansamson',
    html_url: 'https://github.com/morgansamson',
    followers_url: 'https://api.github.com/users/morgansamson/followers',
    following_url:
      'https://api.github.com/users/morgansamson/following{/other_user}',
    gists_url: 'https://api.github.com/users/morgansamson/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/morgansamson/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/morgansamson/subscriptions',
    organizations_url: 'https://api.github.com/users/morgansamson/orgs',
    repos_url: 'https://api.github.com/users/morgansamson/repos',
    events_url: 'https://api.github.com/users/morgansamson/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/morgansamson/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'noplanman',
    id: 9423417,
    node_id: 'MDQ6VXNlcjk0MjM0MTc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9423417?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/noplanman',
    html_url: 'https://github.com/noplanman',
    followers_url: 'https://api.github.com/users/noplanman/followers',
    following_url:
      'https://api.github.com/users/noplanman/following{/other_user}',
    gists_url: 'https://api.github.com/users/noplanman/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/noplanman/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/noplanman/subscriptions',
    organizations_url: 'https://api.github.com/users/noplanman/orgs',
    repos_url: 'https://api.github.com/users/noplanman/repos',
    events_url: 'https://api.github.com/users/noplanman/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/noplanman/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'coreymckrill',
    id: 916023,
    node_id: 'MDQ6VXNlcjkxNjAyMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/916023?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/coreymckrill',
    html_url: 'https://github.com/coreymckrill',
    followers_url: 'https://api.github.com/users/coreymckrill/followers',
    following_url:
      'https://api.github.com/users/coreymckrill/following{/other_user}',
    gists_url: 'https://api.github.com/users/coreymckrill/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/coreymckrill/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/coreymckrill/subscriptions',
    organizations_url: 'https://api.github.com/users/coreymckrill/orgs',
    repos_url: 'https://api.github.com/users/coreymckrill/repos',
    events_url: 'https://api.github.com/users/coreymckrill/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/coreymckrill/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JOJ0',
    id: 2733783,
    node_id: 'MDQ6VXNlcjI3MzM3ODM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2733783?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JOJ0',
    html_url: 'https://github.com/JOJ0',
    followers_url: 'https://api.github.com/users/JOJ0/followers',
    following_url: 'https://api.github.com/users/JOJ0/following{/other_user}',
    gists_url: 'https://api.github.com/users/JOJ0/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/JOJ0/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JOJ0/subscriptions',
    organizations_url: 'https://api.github.com/users/JOJ0/orgs',
    repos_url: 'https://api.github.com/users/JOJ0/repos',
    events_url: 'https://api.github.com/users/JOJ0/events{/privacy}',
    received_events_url: 'https://api.github.com/users/JOJ0/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Jinksi',
    id: 3147296,
    node_id: 'MDQ6VXNlcjMxNDcyOTY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3147296?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Jinksi',
    html_url: 'https://github.com/Jinksi',
    followers_url: 'https://api.github.com/users/Jinksi/followers',
    following_url: 'https://api.github.com/users/Jinksi/following{/other_user}',
    gists_url: 'https://api.github.com/users/Jinksi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Jinksi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Jinksi/subscriptions',
    organizations_url: 'https://api.github.com/users/Jinksi/orgs',
    repos_url: 'https://api.github.com/users/Jinksi/repos',
    events_url: 'https://api.github.com/users/Jinksi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Jinksi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kozer',
    id: 497103,
    node_id: 'MDQ6VXNlcjQ5NzEwMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/497103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kozer',
    html_url: 'https://github.com/kozer',
    followers_url: 'https://api.github.com/users/kozer/followers',
    following_url: 'https://api.github.com/users/kozer/following{/other_user}',
    gists_url: 'https://api.github.com/users/kozer/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kozer/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kozer/subscriptions',
    organizations_url: 'https://api.github.com/users/kozer/orgs',
    repos_url: 'https://api.github.com/users/kozer/repos',
    events_url: 'https://api.github.com/users/kozer/events{/privacy}',
    received_events_url: 'https://api.github.com/users/kozer/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'nirtamir2',
    id: 16452789,
    node_id: 'MDQ6VXNlcjE2NDUyNzg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/16452789?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/nirtamir2',
    html_url: 'https://github.com/nirtamir2',
    followers_url: 'https://api.github.com/users/nirtamir2/followers',
    following_url:
      'https://api.github.com/users/nirtamir2/following{/other_user}',
    gists_url: 'https://api.github.com/users/nirtamir2/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/nirtamir2/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/nirtamir2/subscriptions',
    organizations_url: 'https://api.github.com/users/nirtamir2/orgs',
    repos_url: 'https://api.github.com/users/nirtamir2/repos',
    events_url: 'https://api.github.com/users/nirtamir2/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/nirtamir2/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'noplanman',
    id: 9423417,
    node_id: 'MDQ6VXNlcjk0MjM0MTc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9423417?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/noplanman',
    html_url: 'https://github.com/noplanman',
    followers_url: 'https://api.github.com/users/noplanman/followers',
    following_url:
      'https://api.github.com/users/noplanman/following{/other_user}',
    gists_url: 'https://api.github.com/users/noplanman/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/noplanman/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/noplanman/subscriptions',
    organizations_url: 'https://api.github.com/users/noplanman/orgs',
    repos_url: 'https://api.github.com/users/noplanman/repos',
    events_url: 'https://api.github.com/users/noplanman/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/noplanman/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'coreymckrill',
    id: 916023,
    node_id: 'MDQ6VXNlcjkxNjAyMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/916023?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/coreymckrill',
    html_url: 'https://github.com/coreymckrill',
    followers_url: 'https://api.github.com/users/coreymckrill/followers',
    following_url:
      'https://api.github.com/users/coreymckrill/following{/other_user}',
    gists_url: 'https://api.github.com/users/coreymckrill/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/coreymckrill/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/coreymckrill/subscriptions',
    organizations_url: 'https://api.github.com/users/coreymckrill/orgs',
    repos_url: 'https://api.github.com/users/coreymckrill/repos',
    events_url: 'https://api.github.com/users/coreymckrill/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/coreymckrill/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JOJ0',
    id: 2733783,
    node_id: 'MDQ6VXNlcjI3MzM3ODM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2733783?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JOJ0',
    html_url: 'https://github.com/JOJ0',
    followers_url: 'https://api.github.com/users/JOJ0/followers',
    following_url: 'https://api.github.com/users/JOJ0/following{/other_user}',
    gists_url: 'https://api.github.com/users/JOJ0/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/JOJ0/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JOJ0/subscriptions',
    organizations_url: 'https://api.github.com/users/JOJ0/orgs',
    repos_url: 'https://api.github.com/users/JOJ0/repos',
    events_url: 'https://api.github.com/users/JOJ0/events{/privacy}',
    received_events_url: 'https://api.github.com/users/JOJ0/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Jinksi',
    id: 3147296,
    node_id: 'MDQ6VXNlcjMxNDcyOTY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3147296?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Jinksi',
    html_url: 'https://github.com/Jinksi',
    followers_url: 'https://api.github.com/users/Jinksi/followers',
    following_url: 'https://api.github.com/users/Jinksi/following{/other_user}',
    gists_url: 'https://api.github.com/users/Jinksi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Jinksi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Jinksi/subscriptions',
    organizations_url: 'https://api.github.com/users/Jinksi/orgs',
    repos_url: 'https://api.github.com/users/Jinksi/repos',
    events_url: 'https://api.github.com/users/Jinksi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Jinksi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kozer',
    id: 497103,
    node_id: 'MDQ6VXNlcjQ5NzEwMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/497103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kozer',
    html_url: 'https://github.com/kozer',
    followers_url: 'https://api.github.com/users/kozer/followers',
    following_url: 'https://api.github.com/users/kozer/following{/other_user}',
    gists_url: 'https://api.github.com/users/kozer/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kozer/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kozer/subscriptions',
    organizations_url: 'https://api.github.com/users/kozer/orgs',
    repos_url: 'https://api.github.com/users/kozer/repos',
    events_url: 'https://api.github.com/users/kozer/events{/privacy}',
    received_events_url: 'https://api.github.com/users/kozer/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'nirtamir2',
    id: 16452789,
    node_id: 'MDQ6VXNlcjE2NDUyNzg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/16452789?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/nirtamir2',
    html_url: 'https://github.com/nirtamir2',
    followers_url: 'https://api.github.com/users/nirtamir2/followers',
    following_url:
      'https://api.github.com/users/nirtamir2/following{/other_user}',
    gists_url: 'https://api.github.com/users/nirtamir2/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/nirtamir2/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/nirtamir2/subscriptions',
    organizations_url: 'https://api.github.com/users/nirtamir2/orgs',
    repos_url: 'https://api.github.com/users/nirtamir2/repos',
    events_url: 'https://api.github.com/users/nirtamir2/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/nirtamir2/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'noplanman',
    id: 9423417,
    node_id: 'MDQ6VXNlcjk0MjM0MTc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9423417?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/noplanman',
    html_url: 'https://github.com/noplanman',
    followers_url: 'https://api.github.com/users/noplanman/followers',
    following_url:
      'https://api.github.com/users/noplanman/following{/other_user}',
    gists_url: 'https://api.github.com/users/noplanman/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/noplanman/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/noplanman/subscriptions',
    organizations_url: 'https://api.github.com/users/noplanman/orgs',
    repos_url: 'https://api.github.com/users/noplanman/repos',
    events_url: 'https://api.github.com/users/noplanman/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/noplanman/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'coreymckrill',
    id: 916023,
    node_id: 'MDQ6VXNlcjkxNjAyMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/916023?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/coreymckrill',
    html_url: 'https://github.com/coreymckrill',
    followers_url: 'https://api.github.com/users/coreymckrill/followers',
    following_url:
      'https://api.github.com/users/coreymckrill/following{/other_user}',
    gists_url: 'https://api.github.com/users/coreymckrill/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/coreymckrill/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/coreymckrill/subscriptions',
    organizations_url: 'https://api.github.com/users/coreymckrill/orgs',
    repos_url: 'https://api.github.com/users/coreymckrill/repos',
    events_url: 'https://api.github.com/users/coreymckrill/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/coreymckrill/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JOJ0',
    id: 2733783,
    node_id: 'MDQ6VXNlcjI3MzM3ODM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2733783?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JOJ0',
    html_url: 'https://github.com/JOJ0',
    followers_url: 'https://api.github.com/users/JOJ0/followers',
    following_url: 'https://api.github.com/users/JOJ0/following{/other_user}',
    gists_url: 'https://api.github.com/users/JOJ0/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/JOJ0/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JOJ0/subscriptions',
    organizations_url: 'https://api.github.com/users/JOJ0/orgs',
    repos_url: 'https://api.github.com/users/JOJ0/repos',
    events_url: 'https://api.github.com/users/JOJ0/events{/privacy}',
    received_events_url: 'https://api.github.com/users/JOJ0/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Jinksi',
    id: 3147296,
    node_id: 'MDQ6VXNlcjMxNDcyOTY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3147296?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Jinksi',
    html_url: 'https://github.com/Jinksi',
    followers_url: 'https://api.github.com/users/Jinksi/followers',
    following_url: 'https://api.github.com/users/Jinksi/following{/other_user}',
    gists_url: 'https://api.github.com/users/Jinksi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Jinksi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Jinksi/subscriptions',
    organizations_url: 'https://api.github.com/users/Jinksi/orgs',
    repos_url: 'https://api.github.com/users/Jinksi/repos',
    events_url: 'https://api.github.com/users/Jinksi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Jinksi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kozer',
    id: 497103,
    node_id: 'MDQ6VXNlcjQ5NzEwMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/497103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kozer',
    html_url: 'https://github.com/kozer',
    followers_url: 'https://api.github.com/users/kozer/followers',
    following_url: 'https://api.github.com/users/kozer/following{/other_user}',
    gists_url: 'https://api.github.com/users/kozer/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kozer/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kozer/subscriptions',
    organizations_url: 'https://api.github.com/users/kozer/orgs',
    repos_url: 'https://api.github.com/users/kozer/repos',
    events_url: 'https://api.github.com/users/kozer/events{/privacy}',
    received_events_url: 'https://api.github.com/users/kozer/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'nirtamir2',
    id: 16452789,
    node_id: 'MDQ6VXNlcjE2NDUyNzg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/16452789?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/nirtamir2',
    html_url: 'https://github.com/nirtamir2',
    followers_url: 'https://api.github.com/users/nirtamir2/followers',
    following_url:
      'https://api.github.com/users/nirtamir2/following{/other_user}',
    gists_url: 'https://api.github.com/users/nirtamir2/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/nirtamir2/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/nirtamir2/subscriptions',
    organizations_url: 'https://api.github.com/users/nirtamir2/orgs',
    repos_url: 'https://api.github.com/users/nirtamir2/repos',
    events_url: 'https://api.github.com/users/nirtamir2/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/nirtamir2/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'noplanman',
    id: 9423417,
    node_id: 'MDQ6VXNlcjk0MjM0MTc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9423417?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/noplanman',
    html_url: 'https://github.com/noplanman',
    followers_url: 'https://api.github.com/users/noplanman/followers',
    following_url:
      'https://api.github.com/users/noplanman/following{/other_user}',
    gists_url: 'https://api.github.com/users/noplanman/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/noplanman/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/noplanman/subscriptions',
    organizations_url: 'https://api.github.com/users/noplanman/orgs',
    repos_url: 'https://api.github.com/users/noplanman/repos',
    events_url: 'https://api.github.com/users/noplanman/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/noplanman/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'coreymckrill',
    id: 916023,
    node_id: 'MDQ6VXNlcjkxNjAyMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/916023?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/coreymckrill',
    html_url: 'https://github.com/coreymckrill',
    followers_url: 'https://api.github.com/users/coreymckrill/followers',
    following_url:
      'https://api.github.com/users/coreymckrill/following{/other_user}',
    gists_url: 'https://api.github.com/users/coreymckrill/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/coreymckrill/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/coreymckrill/subscriptions',
    organizations_url: 'https://api.github.com/users/coreymckrill/orgs',
    repos_url: 'https://api.github.com/users/coreymckrill/repos',
    events_url: 'https://api.github.com/users/coreymckrill/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/coreymckrill/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JOJ0',
    id: 2733783,
    node_id: 'MDQ6VXNlcjI3MzM3ODM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2733783?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JOJ0',
    html_url: 'https://github.com/JOJ0',
    followers_url: 'https://api.github.com/users/JOJ0/followers',
    following_url: 'https://api.github.com/users/JOJ0/following{/other_user}',
    gists_url: 'https://api.github.com/users/JOJ0/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/JOJ0/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JOJ0/subscriptions',
    organizations_url: 'https://api.github.com/users/JOJ0/orgs',
    repos_url: 'https://api.github.com/users/JOJ0/repos',
    events_url: 'https://api.github.com/users/JOJ0/events{/privacy}',
    received_events_url: 'https://api.github.com/users/JOJ0/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Jinksi',
    id: 3147296,
    node_id: 'MDQ6VXNlcjMxNDcyOTY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3147296?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Jinksi',
    html_url: 'https://github.com/Jinksi',
    followers_url: 'https://api.github.com/users/Jinksi/followers',
    following_url: 'https://api.github.com/users/Jinksi/following{/other_user}',
    gists_url: 'https://api.github.com/users/Jinksi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Jinksi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Jinksi/subscriptions',
    organizations_url: 'https://api.github.com/users/Jinksi/orgs',
    repos_url: 'https://api.github.com/users/Jinksi/repos',
    events_url: 'https://api.github.com/users/Jinksi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Jinksi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kozer',
    id: 497103,
    node_id: 'MDQ6VXNlcjQ5NzEwMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/497103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kozer',
    html_url: 'https://github.com/kozer',
    followers_url: 'https://api.github.com/users/kozer/followers',
    following_url: 'https://api.github.com/users/kozer/following{/other_user}',
    gists_url: 'https://api.github.com/users/kozer/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kozer/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kozer/subscriptions',
    organizations_url: 'https://api.github.com/users/kozer/orgs',
    repos_url: 'https://api.github.com/users/kozer/repos',
    events_url: 'https://api.github.com/users/kozer/events{/privacy}',
    received_events_url: 'https://api.github.com/users/kozer/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'nirtamir2',
    id: 16452789,
    node_id: 'MDQ6VXNlcjE2NDUyNzg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/16452789?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/nirtamir2',
    html_url: 'https://github.com/nirtamir2',
    followers_url: 'https://api.github.com/users/nirtamir2/followers',
    following_url:
      'https://api.github.com/users/nirtamir2/following{/other_user}',
    gists_url: 'https://api.github.com/users/nirtamir2/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/nirtamir2/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/nirtamir2/subscriptions',
    organizations_url: 'https://api.github.com/users/nirtamir2/orgs',
    repos_url: 'https://api.github.com/users/nirtamir2/repos',
    events_url: 'https://api.github.com/users/nirtamir2/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/nirtamir2/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'noplanman',
    id: 9423417,
    node_id: 'MDQ6VXNlcjk0MjM0MTc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9423417?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/noplanman',
    html_url: 'https://github.com/noplanman',
    followers_url: 'https://api.github.com/users/noplanman/followers',
    following_url:
      'https://api.github.com/users/noplanman/following{/other_user}',
    gists_url: 'https://api.github.com/users/noplanman/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/noplanman/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/noplanman/subscriptions',
    organizations_url: 'https://api.github.com/users/noplanman/orgs',
    repos_url: 'https://api.github.com/users/noplanman/repos',
    events_url: 'https://api.github.com/users/noplanman/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/noplanman/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'coreymckrill',
    id: 916023,
    node_id: 'MDQ6VXNlcjkxNjAyMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/916023?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/coreymckrill',
    html_url: 'https://github.com/coreymckrill',
    followers_url: 'https://api.github.com/users/coreymckrill/followers',
    following_url:
      'https://api.github.com/users/coreymckrill/following{/other_user}',
    gists_url: 'https://api.github.com/users/coreymckrill/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/coreymckrill/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/coreymckrill/subscriptions',
    organizations_url: 'https://api.github.com/users/coreymckrill/orgs',
    repos_url: 'https://api.github.com/users/coreymckrill/repos',
    events_url: 'https://api.github.com/users/coreymckrill/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/coreymckrill/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JOJ0',
    id: 2733783,
    node_id: 'MDQ6VXNlcjI3MzM3ODM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2733783?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JOJ0',
    html_url: 'https://github.com/JOJ0',
    followers_url: 'https://api.github.com/users/JOJ0/followers',
    following_url: 'https://api.github.com/users/JOJ0/following{/other_user}',
    gists_url: 'https://api.github.com/users/JOJ0/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/JOJ0/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JOJ0/subscriptions',
    organizations_url: 'https://api.github.com/users/JOJ0/orgs',
    repos_url: 'https://api.github.com/users/JOJ0/repos',
    events_url: 'https://api.github.com/users/JOJ0/events{/privacy}',
    received_events_url: 'https://api.github.com/users/JOJ0/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Jinksi',
    id: 3147296,
    node_id: 'MDQ6VXNlcjMxNDcyOTY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3147296?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Jinksi',
    html_url: 'https://github.com/Jinksi',
    followers_url: 'https://api.github.com/users/Jinksi/followers',
    following_url: 'https://api.github.com/users/Jinksi/following{/other_user}',
    gists_url: 'https://api.github.com/users/Jinksi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Jinksi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Jinksi/subscriptions',
    organizations_url: 'https://api.github.com/users/Jinksi/orgs',
    repos_url: 'https://api.github.com/users/Jinksi/repos',
    events_url: 'https://api.github.com/users/Jinksi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Jinksi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kozer',
    id: 497103,
    node_id: 'MDQ6VXNlcjQ5NzEwMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/497103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kozer',
    html_url: 'https://github.com/kozer',
    followers_url: 'https://api.github.com/users/kozer/followers',
    following_url: 'https://api.github.com/users/kozer/following{/other_user}',
    gists_url: 'https://api.github.com/users/kozer/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kozer/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kozer/subscriptions',
    organizations_url: 'https://api.github.com/users/kozer/orgs',
    repos_url: 'https://api.github.com/users/kozer/repos',
    events_url: 'https://api.github.com/users/kozer/events{/privacy}',
    received_events_url: 'https://api.github.com/users/kozer/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'nirtamir2',
    id: 16452789,
    node_id: 'MDQ6VXNlcjE2NDUyNzg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/16452789?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/nirtamir2',
    html_url: 'https://github.com/nirtamir2',
    followers_url: 'https://api.github.com/users/nirtamir2/followers',
    following_url:
      'https://api.github.com/users/nirtamir2/following{/other_user}',
    gists_url: 'https://api.github.com/users/nirtamir2/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/nirtamir2/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/nirtamir2/subscriptions',
    organizations_url: 'https://api.github.com/users/nirtamir2/orgs',
    repos_url: 'https://api.github.com/users/nirtamir2/repos',
    events_url: 'https://api.github.com/users/nirtamir2/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/nirtamir2/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'noplanman',
    id: 9423417,
    node_id: 'MDQ6VXNlcjk0MjM0MTc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9423417?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/noplanman',
    html_url: 'https://github.com/noplanman',
    followers_url: 'https://api.github.com/users/noplanman/followers',
    following_url:
      'https://api.github.com/users/noplanman/following{/other_user}',
    gists_url: 'https://api.github.com/users/noplanman/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/noplanman/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/noplanman/subscriptions',
    organizations_url: 'https://api.github.com/users/noplanman/orgs',
    repos_url: 'https://api.github.com/users/noplanman/repos',
    events_url: 'https://api.github.com/users/noplanman/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/noplanman/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'coreymckrill',
    id: 916023,
    node_id: 'MDQ6VXNlcjkxNjAyMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/916023?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/coreymckrill',
    html_url: 'https://github.com/coreymckrill',
    followers_url: 'https://api.github.com/users/coreymckrill/followers',
    following_url:
      'https://api.github.com/users/coreymckrill/following{/other_user}',
    gists_url: 'https://api.github.com/users/coreymckrill/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/coreymckrill/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/coreymckrill/subscriptions',
    organizations_url: 'https://api.github.com/users/coreymckrill/orgs',
    repos_url: 'https://api.github.com/users/coreymckrill/repos',
    events_url: 'https://api.github.com/users/coreymckrill/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/coreymckrill/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JOJ0',
    id: 2733783,
    node_id: 'MDQ6VXNlcjI3MzM3ODM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2733783?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JOJ0',
    html_url: 'https://github.com/JOJ0',
    followers_url: 'https://api.github.com/users/JOJ0/followers',
    following_url: 'https://api.github.com/users/JOJ0/following{/other_user}',
    gists_url: 'https://api.github.com/users/JOJ0/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/JOJ0/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JOJ0/subscriptions',
    organizations_url: 'https://api.github.com/users/JOJ0/orgs',
    repos_url: 'https://api.github.com/users/JOJ0/repos',
    events_url: 'https://api.github.com/users/JOJ0/events{/privacy}',
    received_events_url: 'https://api.github.com/users/JOJ0/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Jinksi',
    id: 3147296,
    node_id: 'MDQ6VXNlcjMxNDcyOTY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3147296?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Jinksi',
    html_url: 'https://github.com/Jinksi',
    followers_url: 'https://api.github.com/users/Jinksi/followers',
    following_url: 'https://api.github.com/users/Jinksi/following{/other_user}',
    gists_url: 'https://api.github.com/users/Jinksi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Jinksi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Jinksi/subscriptions',
    organizations_url: 'https://api.github.com/users/Jinksi/orgs',
    repos_url: 'https://api.github.com/users/Jinksi/repos',
    events_url: 'https://api.github.com/users/Jinksi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Jinksi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kozer',
    id: 497103,
    node_id: 'MDQ6VXNlcjQ5NzEwMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/497103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kozer',
    html_url: 'https://github.com/kozer',
    followers_url: 'https://api.github.com/users/kozer/followers',
    following_url: 'https://api.github.com/users/kozer/following{/other_user}',
    gists_url: 'https://api.github.com/users/kozer/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kozer/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kozer/subscriptions',
    organizations_url: 'https://api.github.com/users/kozer/orgs',
    repos_url: 'https://api.github.com/users/kozer/repos',
    events_url: 'https://api.github.com/users/kozer/events{/privacy}',
    received_events_url: 'https://api.github.com/users/kozer/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'nirtamir2',
    id: 16452789,
    node_id: 'MDQ6VXNlcjE2NDUyNzg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/16452789?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/nirtamir2',
    html_url: 'https://github.com/nirtamir2',
    followers_url: 'https://api.github.com/users/nirtamir2/followers',
    following_url:
      'https://api.github.com/users/nirtamir2/following{/other_user}',
    gists_url: 'https://api.github.com/users/nirtamir2/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/nirtamir2/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/nirtamir2/subscriptions',
    organizations_url: 'https://api.github.com/users/nirtamir2/orgs',
    repos_url: 'https://api.github.com/users/nirtamir2/repos',
    events_url: 'https://api.github.com/users/nirtamir2/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/nirtamir2/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'noplanman',
    id: 9423417,
    node_id: 'MDQ6VXNlcjk0MjM0MTc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9423417?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/noplanman',
    html_url: 'https://github.com/noplanman',
    followers_url: 'https://api.github.com/users/noplanman/followers',
    following_url:
      'https://api.github.com/users/noplanman/following{/other_user}',
    gists_url: 'https://api.github.com/users/noplanman/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/noplanman/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/noplanman/subscriptions',
    organizations_url: 'https://api.github.com/users/noplanman/orgs',
    repos_url: 'https://api.github.com/users/noplanman/repos',
    events_url: 'https://api.github.com/users/noplanman/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/noplanman/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'coreymckrill',
    id: 916023,
    node_id: 'MDQ6VXNlcjkxNjAyMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/916023?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/coreymckrill',
    html_url: 'https://github.com/coreymckrill',
    followers_url: 'https://api.github.com/users/coreymckrill/followers',
    following_url:
      'https://api.github.com/users/coreymckrill/following{/other_user}',
    gists_url: 'https://api.github.com/users/coreymckrill/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/coreymckrill/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/coreymckrill/subscriptions',
    organizations_url: 'https://api.github.com/users/coreymckrill/orgs',
    repos_url: 'https://api.github.com/users/coreymckrill/repos',
    events_url: 'https://api.github.com/users/coreymckrill/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/coreymckrill/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JOJ0',
    id: 2733783,
    node_id: 'MDQ6VXNlcjI3MzM3ODM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2733783?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JOJ0',
    html_url: 'https://github.com/JOJ0',
    followers_url: 'https://api.github.com/users/JOJ0/followers',
    following_url: 'https://api.github.com/users/JOJ0/following{/other_user}',
    gists_url: 'https://api.github.com/users/JOJ0/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/JOJ0/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JOJ0/subscriptions',
    organizations_url: 'https://api.github.com/users/JOJ0/orgs',
    repos_url: 'https://api.github.com/users/JOJ0/repos',
    events_url: 'https://api.github.com/users/JOJ0/events{/privacy}',
    received_events_url: 'https://api.github.com/users/JOJ0/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Jinksi',
    id: 3147296,
    node_id: 'MDQ6VXNlcjMxNDcyOTY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3147296?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Jinksi',
    html_url: 'https://github.com/Jinksi',
    followers_url: 'https://api.github.com/users/Jinksi/followers',
    following_url: 'https://api.github.com/users/Jinksi/following{/other_user}',
    gists_url: 'https://api.github.com/users/Jinksi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Jinksi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Jinksi/subscriptions',
    organizations_url: 'https://api.github.com/users/Jinksi/orgs',
    repos_url: 'https://api.github.com/users/Jinksi/repos',
    events_url: 'https://api.github.com/users/Jinksi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Jinksi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kozer',
    id: 497103,
    node_id: 'MDQ6VXNlcjQ5NzEwMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/497103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kozer',
    html_url: 'https://github.com/kozer',
    followers_url: 'https://api.github.com/users/kozer/followers',
    following_url: 'https://api.github.com/users/kozer/following{/other_user}',
    gists_url: 'https://api.github.com/users/kozer/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kozer/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kozer/subscriptions',
    organizations_url: 'https://api.github.com/users/kozer/orgs',
    repos_url: 'https://api.github.com/users/kozer/repos',
    events_url: 'https://api.github.com/users/kozer/events{/privacy}',
    received_events_url: 'https://api.github.com/users/kozer/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'nirtamir2',
    id: 16452789,
    node_id: 'MDQ6VXNlcjE2NDUyNzg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/16452789?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/nirtamir2',
    html_url: 'https://github.com/nirtamir2',
    followers_url: 'https://api.github.com/users/nirtamir2/followers',
    following_url:
      'https://api.github.com/users/nirtamir2/following{/other_user}',
    gists_url: 'https://api.github.com/users/nirtamir2/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/nirtamir2/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/nirtamir2/subscriptions',
    organizations_url: 'https://api.github.com/users/nirtamir2/orgs',
    repos_url: 'https://api.github.com/users/nirtamir2/repos',
    events_url: 'https://api.github.com/users/nirtamir2/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/nirtamir2/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'noplanman',
    id: 9423417,
    node_id: 'MDQ6VXNlcjk0MjM0MTc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9423417?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/noplanman',
    html_url: 'https://github.com/noplanman',
    followers_url: 'https://api.github.com/users/noplanman/followers',
    following_url:
      'https://api.github.com/users/noplanman/following{/other_user}',
    gists_url: 'https://api.github.com/users/noplanman/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/noplanman/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/noplanman/subscriptions',
    organizations_url: 'https://api.github.com/users/noplanman/orgs',
    repos_url: 'https://api.github.com/users/noplanman/repos',
    events_url: 'https://api.github.com/users/noplanman/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/noplanman/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'coreymckrill',
    id: 916023,
    node_id: 'MDQ6VXNlcjkxNjAyMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/916023?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/coreymckrill',
    html_url: 'https://github.com/coreymckrill',
    followers_url: 'https://api.github.com/users/coreymckrill/followers',
    following_url:
      'https://api.github.com/users/coreymckrill/following{/other_user}',
    gists_url: 'https://api.github.com/users/coreymckrill/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/coreymckrill/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/coreymckrill/subscriptions',
    organizations_url: 'https://api.github.com/users/coreymckrill/orgs',
    repos_url: 'https://api.github.com/users/coreymckrill/repos',
    events_url: 'https://api.github.com/users/coreymckrill/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/coreymckrill/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JOJ0',
    id: 2733783,
    node_id: 'MDQ6VXNlcjI3MzM3ODM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2733783?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JOJ0',
    html_url: 'https://github.com/JOJ0',
    followers_url: 'https://api.github.com/users/JOJ0/followers',
    following_url: 'https://api.github.com/users/JOJ0/following{/other_user}',
    gists_url: 'https://api.github.com/users/JOJ0/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/JOJ0/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JOJ0/subscriptions',
    organizations_url: 'https://api.github.com/users/JOJ0/orgs',
    repos_url: 'https://api.github.com/users/JOJ0/repos',
    events_url: 'https://api.github.com/users/JOJ0/events{/privacy}',
    received_events_url: 'https://api.github.com/users/JOJ0/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Jinksi',
    id: 3147296,
    node_id: 'MDQ6VXNlcjMxNDcyOTY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3147296?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Jinksi',
    html_url: 'https://github.com/Jinksi',
    followers_url: 'https://api.github.com/users/Jinksi/followers',
    following_url: 'https://api.github.com/users/Jinksi/following{/other_user}',
    gists_url: 'https://api.github.com/users/Jinksi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Jinksi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Jinksi/subscriptions',
    organizations_url: 'https://api.github.com/users/Jinksi/orgs',
    repos_url: 'https://api.github.com/users/Jinksi/repos',
    events_url: 'https://api.github.com/users/Jinksi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Jinksi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kozer',
    id: 497103,
    node_id: 'MDQ6VXNlcjQ5NzEwMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/497103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kozer',
    html_url: 'https://github.com/kozer',
    followers_url: 'https://api.github.com/users/kozer/followers',
    following_url: 'https://api.github.com/users/kozer/following{/other_user}',
    gists_url: 'https://api.github.com/users/kozer/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kozer/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kozer/subscriptions',
    organizations_url: 'https://api.github.com/users/kozer/orgs',
    repos_url: 'https://api.github.com/users/kozer/repos',
    events_url: 'https://api.github.com/users/kozer/events{/privacy}',
    received_events_url: 'https://api.github.com/users/kozer/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'nirtamir2',
    id: 16452789,
    node_id: 'MDQ6VXNlcjE2NDUyNzg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/16452789?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/nirtamir2',
    html_url: 'https://github.com/nirtamir2',
    followers_url: 'https://api.github.com/users/nirtamir2/followers',
    following_url:
      'https://api.github.com/users/nirtamir2/following{/other_user}',
    gists_url: 'https://api.github.com/users/nirtamir2/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/nirtamir2/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/nirtamir2/subscriptions',
    organizations_url: 'https://api.github.com/users/nirtamir2/orgs',
    repos_url: 'https://api.github.com/users/nirtamir2/repos',
    events_url: 'https://api.github.com/users/nirtamir2/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/nirtamir2/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'noplanman',
    id: 9423417,
    node_id: 'MDQ6VXNlcjk0MjM0MTc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9423417?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/noplanman',
    html_url: 'https://github.com/noplanman',
    followers_url: 'https://api.github.com/users/noplanman/followers',
    following_url:
      'https://api.github.com/users/noplanman/following{/other_user}',
    gists_url: 'https://api.github.com/users/noplanman/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/noplanman/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/noplanman/subscriptions',
    organizations_url: 'https://api.github.com/users/noplanman/orgs',
    repos_url: 'https://api.github.com/users/noplanman/repos',
    events_url: 'https://api.github.com/users/noplanman/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/noplanman/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'coreymckrill',
    id: 916023,
    node_id: 'MDQ6VXNlcjkxNjAyMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/916023?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/coreymckrill',
    html_url: 'https://github.com/coreymckrill',
    followers_url: 'https://api.github.com/users/coreymckrill/followers',
    following_url:
      'https://api.github.com/users/coreymckrill/following{/other_user}',
    gists_url: 'https://api.github.com/users/coreymckrill/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/coreymckrill/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/coreymckrill/subscriptions',
    organizations_url: 'https://api.github.com/users/coreymckrill/orgs',
    repos_url: 'https://api.github.com/users/coreymckrill/repos',
    events_url: 'https://api.github.com/users/coreymckrill/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/coreymckrill/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JOJ0',
    id: 2733783,
    node_id: 'MDQ6VXNlcjI3MzM3ODM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2733783?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JOJ0',
    html_url: 'https://github.com/JOJ0',
    followers_url: 'https://api.github.com/users/JOJ0/followers',
    following_url: 'https://api.github.com/users/JOJ0/following{/other_user}',
    gists_url: 'https://api.github.com/users/JOJ0/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/JOJ0/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JOJ0/subscriptions',
    organizations_url: 'https://api.github.com/users/JOJ0/orgs',
    repos_url: 'https://api.github.com/users/JOJ0/repos',
    events_url: 'https://api.github.com/users/JOJ0/events{/privacy}',
    received_events_url: 'https://api.github.com/users/JOJ0/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Jinksi',
    id: 3147296,
    node_id: 'MDQ6VXNlcjMxNDcyOTY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3147296?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Jinksi',
    html_url: 'https://github.com/Jinksi',
    followers_url: 'https://api.github.com/users/Jinksi/followers',
    following_url: 'https://api.github.com/users/Jinksi/following{/other_user}',
    gists_url: 'https://api.github.com/users/Jinksi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Jinksi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Jinksi/subscriptions',
    organizations_url: 'https://api.github.com/users/Jinksi/orgs',
    repos_url: 'https://api.github.com/users/Jinksi/repos',
    events_url: 'https://api.github.com/users/Jinksi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Jinksi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kozer',
    id: 497103,
    node_id: 'MDQ6VXNlcjQ5NzEwMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/497103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kozer',
    html_url: 'https://github.com/kozer',
    followers_url: 'https://api.github.com/users/kozer/followers',
    following_url: 'https://api.github.com/users/kozer/following{/other_user}',
    gists_url: 'https://api.github.com/users/kozer/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kozer/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kozer/subscriptions',
    organizations_url: 'https://api.github.com/users/kozer/orgs',
    repos_url: 'https://api.github.com/users/kozer/repos',
    events_url: 'https://api.github.com/users/kozer/events{/privacy}',
    received_events_url: 'https://api.github.com/users/kozer/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'nirtamir2',
    id: 16452789,
    node_id: 'MDQ6VXNlcjE2NDUyNzg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/16452789?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/nirtamir2',
    html_url: 'https://github.com/nirtamir2',
    followers_url: 'https://api.github.com/users/nirtamir2/followers',
    following_url:
      'https://api.github.com/users/nirtamir2/following{/other_user}',
    gists_url: 'https://api.github.com/users/nirtamir2/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/nirtamir2/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/nirtamir2/subscriptions',
    organizations_url: 'https://api.github.com/users/nirtamir2/orgs',
    repos_url: 'https://api.github.com/users/nirtamir2/repos',
    events_url: 'https://api.github.com/users/nirtamir2/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/nirtamir2/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'noplanman',
    id: 9423417,
    node_id: 'MDQ6VXNlcjk0MjM0MTc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9423417?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/noplanman',
    html_url: 'https://github.com/noplanman',
    followers_url: 'https://api.github.com/users/noplanman/followers',
    following_url:
      'https://api.github.com/users/noplanman/following{/other_user}',
    gists_url: 'https://api.github.com/users/noplanman/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/noplanman/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/noplanman/subscriptions',
    organizations_url: 'https://api.github.com/users/noplanman/orgs',
    repos_url: 'https://api.github.com/users/noplanman/repos',
    events_url: 'https://api.github.com/users/noplanman/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/noplanman/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'coreymckrill',
    id: 916023,
    node_id: 'MDQ6VXNlcjkxNjAyMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/916023?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/coreymckrill',
    html_url: 'https://github.com/coreymckrill',
    followers_url: 'https://api.github.com/users/coreymckrill/followers',
    following_url:
      'https://api.github.com/users/coreymckrill/following{/other_user}',
    gists_url: 'https://api.github.com/users/coreymckrill/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/coreymckrill/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/coreymckrill/subscriptions',
    organizations_url: 'https://api.github.com/users/coreymckrill/orgs',
    repos_url: 'https://api.github.com/users/coreymckrill/repos',
    events_url: 'https://api.github.com/users/coreymckrill/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/coreymckrill/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JOJ0',
    id: 2733783,
    node_id: 'MDQ6VXNlcjI3MzM3ODM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2733783?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JOJ0',
    html_url: 'https://github.com/JOJ0',
    followers_url: 'https://api.github.com/users/JOJ0/followers',
    following_url: 'https://api.github.com/users/JOJ0/following{/other_user}',
    gists_url: 'https://api.github.com/users/JOJ0/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/JOJ0/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JOJ0/subscriptions',
    organizations_url: 'https://api.github.com/users/JOJ0/orgs',
    repos_url: 'https://api.github.com/users/JOJ0/repos',
    events_url: 'https://api.github.com/users/JOJ0/events{/privacy}',
    received_events_url: 'https://api.github.com/users/JOJ0/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Jinksi',
    id: 3147296,
    node_id: 'MDQ6VXNlcjMxNDcyOTY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3147296?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Jinksi',
    html_url: 'https://github.com/Jinksi',
    followers_url: 'https://api.github.com/users/Jinksi/followers',
    following_url: 'https://api.github.com/users/Jinksi/following{/other_user}',
    gists_url: 'https://api.github.com/users/Jinksi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Jinksi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Jinksi/subscriptions',
    organizations_url: 'https://api.github.com/users/Jinksi/orgs',
    repos_url: 'https://api.github.com/users/Jinksi/repos',
    events_url: 'https://api.github.com/users/Jinksi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Jinksi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kozer',
    id: 497103,
    node_id: 'MDQ6VXNlcjQ5NzEwMw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/497103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kozer',
    html_url: 'https://github.com/kozer',
    followers_url: 'https://api.github.com/users/kozer/followers',
    following_url: 'https://api.github.com/users/kozer/following{/other_user}',
    gists_url: 'https://api.github.com/users/kozer/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kozer/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kozer/subscriptions',
    organizations_url: 'https://api.github.com/users/kozer/orgs',
    repos_url: 'https://api.github.com/users/kozer/repos',
    events_url: 'https://api.github.com/users/kozer/events{/privacy}',
    received_events_url: 'https://api.github.com/users/kozer/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'nirtamir2',
    id: 16452789,
    node_id: 'MDQ6VXNlcjE2NDUyNzg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/16452789?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/nirtamir2',
    html_url: 'https://github.com/nirtamir2',
    followers_url: 'https://api.github.com/users/nirtamir2/followers',
    following_url:
      'https://api.github.com/users/nirtamir2/following{/other_user}',
    gists_url: 'https://api.github.com/users/nirtamir2/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/nirtamir2/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/nirtamir2/subscriptions',
    organizations_url: 'https://api.github.com/users/nirtamir2/orgs',
    repos_url: 'https://api.github.com/users/nirtamir2/repos',
    events_url: 'https://api.github.com/users/nirtamir2/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/nirtamir2/received_events',
    type: 'User',
    site_admin: false,
  },
]
